[package]
name = "bbb_core"
version = "1.0.1"
authors = ["Danny Clarke <danny.clarke@gimbal.com>"]

[dependencies]
sample = "0.7.1"
portaudio = "0.7.0"
hound = "3.2.0"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
